
public class ThrowingException {

	public static void main(String[] args) {
		Person person = new Person(12);
		
		try {
			
		} catch (IllegalArgumentException exception) {
			System.out.println("Възникна грешка: " + exception.getMessage());
		}

	}

}
